name: mplayer
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/covers/
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.jpeg"  
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"                
  image: assets/icon/icon.jpeg   
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: scaleAspectFit
