name: mplayer
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  audioplayers: ^6.5.1
  file_picker: ^10.3.10
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  path_provider: ^2.1.5
  permission_handler: ^12.0.1

  # audioplayers: ^5.2.0        # For audio playback
  # file_picker: ^6.1.1         # For folder selection
  # permission_handler: ^11.0.1 # For storage permission (Android)
  # path_provider: ^2.1.1       # For getting correct paths
  # (optional) audio_metadata_reader: ^0.4.0  # If you want to read title/artist from file metadata

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/covers/
    - assets/audio/
    - assets/icon/ 
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.jpeg"  
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"                
  image: assets/icon/icon.jpeg   
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: scaleAspectFit
